### ISSUE TITLE
Question: is St Wenceslaus patron of whole Czech Republic or just of Czechia (Moravia not including)?

### ISSUE THREAD

**Issue by tukusejssirs** [igneus/calendarium-romanum#72]
In [`czech-cs.txt` (L194)](https://github.com/igneus/calendarium-romanum/blob/154450eec9d50771c30a3f1c02cfe7d3373d605a/data/czech-cs.txt#L194), there is the following line:

```js
Sv. Václava, mučedníka, hlavního patrona českého národa
```

Is St Wenceslaus patron of whole Czech Republic or just of Czechia (Moravia not including)? I have no idea if Moravians are included in the Czech _nation_ or not.

**Comment by igneus** [comment]
> I have no idea if Moravians are included in the Czech nation or not.

I only dispute it when talking to Moravians. Since I believe you are not a Moravian: yes, Moravians are definitely included in the Czech nation.

Btw. a "patron of the Czech *nation*" is a post-Vatican II novelty, IMO not a particularly fortunate one.

Until the liturgical reform, most of today's Czech Republic belonged to one of two ecclesiastical provinces (of Prague and Olomouc), each having it's own calendar (and propers) and it's own set of patrons, at least in Prague quite ample and hierarchically ordered in two or three (changed in time) orders: patroni principales / minus principales / secundarii. The patrons celebrated in the province of Prague all held (in the liturgical calendar) the title of "patroni *regni Bohemiae*" (of the kingdom of Bohemia), later, after the republic was established, simply "patroni *Bohemiae*", i.e. patrons of a territory. For Moravia I would have to do some research (I have the books, but I can't do it right now), but I can say at least that St. Wenceslas was celebrated there as "titular of the Olomouc cathedral and principal patron *of the archdiocese*", i.e. also as their local/territorial patron.

The liturgical reform of Vatican II for the first time in history "liturgically united" Bohemia and Moravia, producing a common "national" liturgical calendar and propers - and a single (much smaller) shared set of patrons, now distributed among various subjects:

* St. Wenceslas becomes principal patron of a nation
* St. John of Nepomuk and Sts. Cyril and Methodius principal patrons of Bohemia and Moravia, respectively
* St. Adalbert, once secondary patron of Bohemia, becomes principal patron of the archdiocese of Prague (only)

(The other pre-conciliar patrons of Bohemia mostly ceased to be official patrons, now they are just saints inscribed in the calendar of dioceses of Bohemia and Moravia.)

**Comment by tukusejssirs** [comment]
Thanks for the thorough answer. I simply wish you’d work on romcal (I know you probably won’t switch projects). :wink:

**Comment by igneus** [comment]
> (I know you probably won’t switch projects)

Of course I won't. I strongly believe in calendarium-romanum's concept. And competition fosters quality.
