### ISSUE TITLE
Possibly incorrect grammar case used for `Jiří`

### ISSUE THREAD

**Issue by tukusejssirs** [igneus/calendarium-romanum#74]
According to [sklonuj.cz](https://sklonuj.cz/slovo/Ji%C5%99%C3%AD), the genitive singular of `Jiří` is `Jiřího`. I don’t say that website is absolutely correct, but it looks like it is correct.

The relevant line is located in [`czech-cs.txt` (L63)](https://github.com/igneus/calendarium-romanum/blob/d4286b80cfb8cd77a4d6bf116e26399230ff9ae4/data/czech-cs.txt#L63).

**Comment by igneus** [comment]
No. https://prirucka.ujc.cas.cz/?slovo=Ji%C5%99%C3%AD

"Čí je to kolo?" _"Jiřího."_ ("regular" genitive)
but
"svátek svatého _Jiří_" (uninflected genitive used in some specific contexts - "svátek svatého Jiřího")

**Comment by tukusejssirs** [comment]
Thanks for the explanation. Sorry for reporting non-existing issues.

**Comment by igneus** [comment]
Ouch, I left the sentence in parentheses unfinished: I wanted to say that "svátek svatého *Jiřího*" (the regular genitive in the particular context) would sound very strange, signalling that the speaker is either non-native or not familiar with this layer of the language (probably lacks education above the elementary level, has not read much etc.).

**Comment by igneus** [comment]
Fun fact: the form "Jiřího" is used in the [calendar of Czech Old Catholic Church](https://github.com/calendarium-romanum/czech_old_catholic_calendar/blob/master/data/general.txt#L38). The archaic genitive "svatého _Jiří_" is usually tied to this very phrase and since the calendar does not use the title "Saint", it doesn't use the name's archaic genitive either.
