### ISSUE TITLE
Same celebration yields different colours?

### ISSUE THREAD

**Issue by JOyo246** [igneus/calendarium-romanum#99]
(Please excuse my ignorance as this I'm a front-end dev, trying to use my own server instance.)

For July 20, 2024, St Apollinaris has different colours from different sources, (note, i may be missing something)
http://local/api/v0/fr/calendars/general-fr/2024/7/20 - "red"
http://local/api/v0/en/calendars/default/2024/7/20  - "white"
http://calapi.inadiutorium.cz/api/v0/en/calendars/default/2024/7/20  - "red"

I'm actively investigating to see why my local english instance is "white", but if i could be pointed in the right direction, that would be much appreciated.

Thanks for all of you hard work @igneus!

**Comment by igneus** [comment]
This will be due to an inconsistency in calendar data. Colours are specified in the sanctorale data files and each language has a separate one. If you are using a local installation of https://github.com/igneus/church-calendar-api , it is still locked to an old version of `calendarium-romanum` (I haven't touched that app for several years now). If you manage to update to the latest `calendarium-romanum` version (update version specified in `Gemfile`, run `bundle install`, if the application crashes, fix it), the inconsistency will be gone. Data quality has been improved.
